import { Inter } from 'next/font/google'
import './globals.scss'
import Cabecalho from '@/components/cabecalho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inova - X Care',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Cabecalho/>
        {children}
      </body>
    </html>
  )
}
